server.port=8084
spring.application.name=CART-SERVICE

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=cart-service
eureka.instance.prefer-ip-address=true

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://cartuser:cartpass@localhost:27021/cartdb?authSource=admin

# JWT Configuration
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin

# Docker Compose
spring.docker.compose.enabled=false
