server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  docker:
    compose:
      enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
            - "http://localhost:3001"
            - "http://localhost:3000"
            - "http://127.0.0.1:3001"
            - "http://127.0.0.1:3000"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka