spring.application.name=user-service

server.port=8082

spring.docker.compose.enabled=false

# MongoDB Database Configuration
spring.data.mongodb.uri=mongodb://useruser:userpass@localhost:27018/?authSource=admin
spring.data.mongodb.database=userdb

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
